name: Deploy to dev env
on:
  workflow_dispatch:

  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: set all env vars from env
        env:
          all_vars: ${{ toJson(vars) }}
        run: echo "$all_vars"

  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: step1
        run: echo "=====Deployment to heroku started======="

      - name: Push to heroku
        run: git push -f https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ vars.HEROKU_DEV_NAME }}.git origin/dev:master



  
